export const compareDialogCopy = {
	bg: {
		description: 'Цена и характеристики.',
		chooseDescription: 'Избери от 2 до 4 автомобила за сравнение.',
		select: 'Избери автомобил',
		selection: 'Избрани автомобили',
		selected: 'Избрани: {count} от 4',
		chooseMore: 'Избери поне 2 автомобила',
		compare: 'Сравни ({count})',
		edit: 'Промени избора',
		differences: 'Само разликите',
		same: 'Тези характеристики съвпадат при избраните автомобили.',
		copyLink: 'Копирай линк',
		copied: 'Копирано',
		copyFailed: 'Отвори сравнението, за да копираш адреса.',
		search: 'Търси автомобил за сравнение',
		placeholder: 'Марка, модел или година',
		noResults: 'Няма намерени автомобили',
		clearSearch: 'Изчисти търсенето',
		loading: 'Зареждаме автомобилите…',
		failed: 'Не успяхме да заредим автомобилите.',
		retry: 'Опитай отново',
		page: 'Отвори като страница',
		close: 'Готово'
	},
	en: {
		description: 'Price and specifications.',
		chooseDescription: 'Choose 2 to 4 cars to compare.',
		select: 'Select car',
		selection: 'Selected cars',
		selected: '{count} of 4 selected',
		chooseMore: 'Choose at least 2 cars',
		compare: 'Compare ({count})',
		edit: 'Change selection',
		differences: 'Only differences',
		same: 'These specifications match for the selected cars.',
		copyLink: 'Copy link',
		copied: 'Copied',
		copyFailed: 'Open the comparison to copy its address.',
		search: 'Search cars to compare',
		placeholder: 'Make, model or year',
		noResults: 'No matching cars',
		clearSearch: 'Clear search',
		loading: 'Loading cars…',
		failed: 'We couldn’t load the cars.',
		retry: 'Try again',
		page: 'Open as a page',
		close: 'Done'
	}
};
