"""Generate delivery subsets without changing Sofia Sans glyph metrics or licensing.

Optional asset maintenance: Python with fonttools 4.66.1 and brotli 1.2.0.
The application itself still uses the documented Node runtime.
"""

from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

project = Path(__file__).resolve().parents[1]
root = project / "static" / "fonts" / "sofia-sans"
ranges = {
    "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0300-036F,U+2000-206F,U+20A0-20CF,U+2113,U+2122,U+2190-21FF,U+2212,U+FEFF,U+FFFD",
    "cyrillic": "U+0400-052F,U+2DE0-2DFF,U+A640-A69F",
}
faces = [
    (family, weight, f"{stem}-{style}")
    for family, stem in [
        ("Sofia Sans", "SofiaSans"),
        ("Sofia Sans SemiCondensed", "SofiaSansSemiCondensed"),
    ]
    for weight, style in [(400, "Regular"), (600, "SemiBold"), (700, "Bold")]
]

css = [
    "/* Sofia Sans: official Lettersoup sources, SIL OFL 1.1 (./OFL.txt).",
    " * Delivery subsets are generated by scripts/subset-fonts.py.",
    " * Full originals remain the fallback for other scripts. */",
]

def face(family, weight, filename, unicode_range=None):
    rule = [
        "@font-face {",
        f"\tfont-family: '{family}';",
        f"\tsrc: url('./{filename}.woff2') format('woff2');",
        "\tfont-style: normal;",
        f"\tfont-weight: {weight};",
        "\tfont-display: swap;",
    ]
    if unicode_range:
        rule.append(f"\tunicode-range: {unicode_range};")
    return "\n".join(rule + ["}"])

for family, weight, filename in faces:
    css.append(face(family, weight, filename))
    original = TTFont(root / f"{filename}.woff2", recalcTimestamp=False)
    original_cmap = original.getBestCmap()
    for script, unicode_range in ranges.items():
        font = TTFont(root / f"{filename}.woff2", recalcTimestamp=False)
        options = subset.Options()
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.name_legacy = True
        options.name_languages = ["*"]
        options.notdef_glyph = True
        options.notdef_outline = True
        tool = subset.Subsetter(options=options)
        tool.populate(unicodes=subset.parse_unicodes(unicode_range))
        tool.subset(font)
        output = root / f"{filename}.{script}.woff2"
        font.save(output)
        # Every delivered glyph keeps the exact source advance width and side bearing.
        for codepoint, glyph in font.getBestCmap().items():
            assert font["hmtx"][glyph] == original["hmtx"][original_cmap[codepoint]]
        css.append(face(family, weight, f"{filename}.{script}", unicode_range))
        print(f"{output.name}: {output.stat().st_size} bytes")
    original.close()

stylesheet = "\n\n".join(css) + "\n"
(root / "fonts.css").write_text(stylesheet, encoding="utf-8")
# Keep the bundled stylesheet in Vite's source boundary, with public asset URLs.
# The relative-path copy remains available beside the font files for compatibility.
(project / "src" / "lib" / "styles" / "fonts.css").write_text(
    stylesheet.replace("url('./", "url('/fonts/sofia-sans/").replace(
        "(./OFL.txt)", "(static/fonts/sofia-sans/OFL.txt)"
    ),
    encoding="utf-8",
)
